#!/usr/bin/env bash

# assign variables for author, reponame and releaseversion
author="$(echo "$2" | cut -d '/' -f1)"
reponame="$(echo "$2" | cut -d '/' -f2)"
releasever="$(rpm -E %fedora)"
repofile="/etc/yum.repos.d/_copr_$author-$reponame.repo"
repofilebak="$HOME/COPR/_copr_$author-$reponame.repo"

# The original COPR warning message
question=$(
        cat <<EOF
Enabling a Copr repository. Please note that this repository is not part
of the main distribution, and quality may vary.

The Fedora Project does not exercise any power over the contents of
this repository beyond the rules outlined in the Copr FAQ at
<https://docs.pagure.org/copr.copr/user_documentation.html#what-i-can-build-in-copr>,
and packages are not held to any quality or security level.

Please do not file bug reports about these packages in Fedora
Bugzilla. In case of problems, contact the owner of this repository.

Do you really want to enable copr.fedorainfracloud.org/$author/$reponame? [y/N]:
EOF
)

# the helptext
helptext=$(
        cat <<EOF

====== Experimental COPR Command in non-DNF Fedora Distributions ======

This Tool is not made or supported by the Fedora Project,
but aims to reproduce the "dnf copr" functionalities for easily adding COPRs.

Usage: copr [OPTION] [ARGUMENT]

Options:
  enable    Add COPR repository
  disable   Keep a repo but disable it
  remove    Remove COPR repository after backing it up
  list      List all COPR repositories in your repo folder
  search    Search for a COPR repository by name (in your Browser)
  help      Display this help text

Argument:
  Name of the COPR repository (for search) or "author/repo" (for install and remove)

Examples:
  copr enable kdesig/kde-nightly-qt6
  copr remove kdesig/kde-nightly-qt6
  copr list
  copr search bubblejail

For help, write me here: https://discussion.fedoraproject.org/u/boredsquirrel/

EOF
)

##### SECURE REPO FILES #####
# changing unix permissions to make them root-owned and read-only by world
# chang SELinux labels to "system_u:object_r:system_conf_t:s0" like the default Fedora repos

secure-files () {
        echo "Securing the repo files against manipulation. Please enter your password one last time."
        pkexec sh -c "
        chown root:root /etc/yum.repos.d/* && \
        chmod 744 /etc/yum.repos.d/* && \
        chcon -R system_u:object_r:system_conf_t:s0 /etc/yum.repos.d/
        " || {
                echo "Failed to secure the repo files!"
                exit 1
        }
}

move-repo () {
        # check if backup dir exists, create it when needed
        [ ! -d "$HOME/COPR" ] && mkdir -p "$HOME/COPR"

        pkexec sh -c '
                mv "$result" "$repofilebak" &&\
                chown "$USER" "$repofilebak" &&\
                echo 'COPR Repository "$reponame" removed.' ||\
                echo "ERROR removing COPR repository."
        '
}

# Main loop

if [[ "$1" == "enable" ]]; then
        while true; do
                read -rp "$question" yn
                case $yn in
                [Yy]*)
                        # test if the repo file already exists
                        if [[ -e "$repofile" ]]; then
                                # set the repo to active
                                pkexec sed -i 's/enabled=0/enabled=1/g' "$repofile" && echo "Repository $author/$reponame enabled" || echo "Already enabled or repo not found."
                        else
                                # download the repofile
                                echo "$author/$reponame -> $releasever"
                                curl -fsSL "https://copr.fedorainfracloud.org/coprs/$author/$reponame/repo/fedora-$releasever/$author-$reponame-fedora.repo" | pkexec tee "$repofile" >/dev/null
                                secure-files
                        fi
                        break
                        ;;
                *)
                        echo "Unknown option, exiting."
                        break
                        ;;
                esac
        done

# disable a repo
elif [[ "$1" == "disable" ]]; then
        secure-files
        sed 's/enabled=1/enabled=0/g' "$repofile" >/dev/null &&
                echo "Repository "$author"/"$reponame" disabled." ||
                echo "Already disabled or repo not found."

# remove the named repo
elif [[ "$1" == "remove" ]]; then

        if [[ -e "$repofile" ]]; then
                move-repo
        else
                # search for the reponame
                echo 'Repo with name "$author"/"$reponame"" not found, trying a search...'
                repofile=$(grep -ril --include='*.repo' "$reponame" /etc/yum.repos.d/)

                # if not found, exit
                if [[ -z "$result" ]]; then
                        echo 'No repositories containing "$reponame" were found.'
                        exit 1
                else
                        # if found, make sure it is the right one
                        read -rp 'Repo "$result" was found. Do you want to backup and remove this repo? (y/N) ' answer
                        if [[ "${answer,,}" == "y" ]]; then
                                move-repo
                        else
                                exit 1
                        fi
                fi
        fi

# list all installed COPR repositories
elif [[ "$1" == "list" ]]; then
        find /etc/yum.repos.d/ -type f -name '_copr*' -exec basename {} \; | sed 's/_copr_//; s/\.repo$//'

# search, this is just implemented through the browser (hey, pip does the same!)
elif [[ "$1" == "search" ]]; then
        xdg-open "https://copr.fedorainfracloud.org/coprs/fulltext/?fulltext=$2"

# display the helptext
elif [[ "$1" == "-h" || "$1" == "--h" || "$1" == "-help" || "$1" == "--help" || "$1" == "help" ]]; then
        echo "$helptext"
fi
